language: python
python:
  - "3.7"
  - "3.8"
  - "3.9-dev"
matrix:
  allow_failures:
    - python: "3.9-dev"
before_install: true
install:
  - pip install -U pip
  - pip install -U setuptools
script:
  - python setup.py flake8
  - python setup.py test
